---
dependency:
  name: galaxy
  enabled: False
driver:
  name: docker
platforms:
  - name: centos6
    image: centos:centos6
    exposed_ports:
      - 80/tcp
    published_ports:
      - 0.0.0.0:8080:80/tcp
  - name: centos7
    image: centos:centos7
    privileged: True
    command: '/usr/lib/systemd/systemd'
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    exposed_ports:
      - 80/tcp
    published_ports:
      - 0.0.0.0:8081:80/tcp
lint:
  name: yamllint
  enabled: False
provisioner:
  name: ansible
  playbooks:
    create: create.yml
    converge: playbook.yml
    destroy: destroy.yml
  lint:
    name: ansible-lint
    force-color: True
scenario:
  name: default
verifier:
  name: testinfra
  options:
    #'junit-xml': reports/junit.xml
    n: 5
  lint:
    name: flake8
    enabled: True
