require 'spec_helper'

describe file('/etc/httpd/conf/ports.conf') do
  it { should be_file }
  it { should be_mode 644 }
  it { should be_owned_by 'root' }
  it { should be_grouped_into 'root' }
  its(:content) { should contain '# Ansible managed: Do NOT edit this file manually!' }
  its(:content) { should contain 'Listen 80' }
  its(:content) { should contain 'Listen 443' }
end

describe file('/etc/httpd/conf/httpd.conf') do
  it { should be_file }
  it { should be_mode 644 }
  it { should be_owned_by 'root' }
  it { should be_grouped_into 'root' }
  it { should contain '# Ansible managed: Blocks of this file are managed' }
  its(:content) { should contain '# Ansible managed: Blocks of this file are managed' }
  its(:content) { should_not match(/^Listen.*/) }
end

describe file('/etc/httpd/conf.d/ssl.conf') do
  it { should be_file }
  its(:content) { should_not match(%r{<VirtualHost.*>[\w\W]*?</VirtualHost>}) }
end

describe file('/etc/httpd/conf.d/fqdn.conf') do
  it { should be_file }
  it { should be_mode 644 }
  it { should be_owned_by 'root' }
  it { should be_grouped_into 'root' }
  its(:content) { should contain 'ServerName localhost' }
end

describe user('apache') do
  it { should exist }
  it { should belong_to_group 'apache' }
end

describe group('apache') do
  it { should exist }
end
