require 'spec_helper'

describe file('/etc/httpd/conf.d/localhost_ssl.conf') do
  it { should be_file }
  it { should be_mode 644 }
  it { should be_owned_by 'root' }
  it { should be_grouped_into 'root' }
  its(:content) { should contain '# Ansible managed: Do NOT edit this file manually!' }
end

describe file('/etc/httpd/conf.d/localhost_non_ssl.conf') do
  it { should be_file }
  it { should be_mode 644 }
  it { should be_owned_by 'root' }
  it { should be_grouped_into 'root' }
  its(:content) { should contain '# Ansible managed: Do NOT edit this file manually!' }
end
