import pytest
import os
import testinfra.utils.ansible_runner
testinfra_hosts = testinfra.utils.ansible_runner.AnsibleRunner(
    os.environ['MOLECULE_INVENTORY_FILE']).get_hosts('all')


@pytest.mark.parametrize("name, user, group, mode, content", [
    (
        "/etc/httpd/conf.d/localhost_ssl.conf", "root", "root", "0644",
        "# Ansible managed: Do NOT edit this file manually!"
    ),
    (
        "/etc/httpd/conf.d/localhost_non_ssl.conf", "root", "root", "0644",
        "# Ansible managed: Do NOT edit this file manually!"
    ),
])
def test_apache_vhosts(host, name, user, group, mode, content):
    file = host.file("{}".format(name))
    assert file.is_file
    assert file.user == user
    assert file.group == group
    assert oct(file.mode) == mode
    assert "{}".format(content) in file.content
